# linear intrepolation

In [1]:
# linear intrepolation
from scipy.interpolate import interp1d
 
X = [0,3] #  x values 0 and 3
Y = [2,5] # y values at 0, 3 resp
 
# test value
interpolate_x = 2
 
# Finding the interpolation
y_interp = interp1d(X, Y)
print("Value of Y at x = {} is".format(interpolate_x),
      y_interp(interpolate_x))

Value of Y at x = 2 is 4.0


# Rotation Matrix (Spatial Transformations)

In [2]:
from scipy.spatial.transform import Rotation as R
import numpy as np

vec = [3,2,0]

rotation_degrees = 30
rotation_radians = np.radians(rotation_degrees)
rotation_axis = np.array([0, 0, 1])

rotation_vector = rotation_radians * rotation_axis
rotation = R.from_rotvec(rotation_vector)
rotated_vec = rotation.apply(vec)

print(rotated_vec)

[1.59807621 3.23205081 0.        ]


In [17]:
#  Single line code.
r = R.from_rotvec(30 * np.array([0, 0, 1]), degrees=True)
rotated_vec = r.apply([3,2,0])
rotated_vec


array([1.59807621, 3.23205081, 0.        ])

#  Translation


In [18]:
#  Translation
translation_vec=[5,7,0]
translated_vec=rotated_vec+translation_vec
translated_vec

array([ 6.59807621, 10.23205081,  0.        ])

# Interpolation of a polynomial of the form:

In [3]:
from math import sin, cos

def fx_calc(x):
        fx=[1,x,x**2]  ##fx_ function coefficients of a's
#         print(fx)
        return fx

def fy_calc(x):
        y= (x**2)/10 -2*sin(x)   ##fy_ function value of y
        
        return y    
    
        
    
x_val=[0,1,2]
fx_matrix=[]
fy=[]
for i in x_val:
    fx_matrix.append(fx_calc(i))
    fy.append(fy_calc(i))

# convereting into matrix form
fx_matrix=np.reshape(fx_matrix,(len(x_val),len(x_val)))
# print(fx_matrix)
# print(fy)
# resape  to convert into column matrix
fy_t=np.reshape(fy,(len(x_val),1))
# print(fy_t)
#  taking inverse
fx_inverse=np.linalg.inv(fx_matrix)

# multiplying we get fx_inv*fy

print(np.matrix(fx_inverse)*np.matrix(fy_t))


#  valuse of a's are

[[ 0.        ]
 [-2.45658651]
 [ 0.87364454]]


# Homogenous Co-ordinates


In [12]:
non_homogenous=[5,7]
homogenous = non_homogenous
homogenous.append(1)
print(homogenous)

[5, 7, 1]


# Intersecting planes

In [27]:
# vec r= r0+ vec d* t    some scalar
# 2x+y−z=3; x-y+z=3?
# setting z=0

A = np.array([[2, 1], [1, -1]])
B = np.array([3, 3])
X = np.linalg.solve(A,B)
X=X+[0]


E1=np.array([2,1,-1])
E2=np.array([1,-1,1])
product_vec=np.cross(E1,E2)
print(X,"+ t" ,product_vec)


[ 2. -1.] + t [ 0 -3 -3]


# intersection of lines in HC

in homogenous Cordinates intersection of two lines is given by
x = l ∩ m : x = l × m

In [28]:
# 3x+2y+1=0 and 6x+4y−2=0.

L=[3,2,1]
M=[6,4,-2]

#  intersection is 
X=np.cross(np.array(L),np.array(M))
X
#  the same cannot be expressed in Eucledian Space


array([-8, 12,  0])

# transforation Matrix

In [6]:
from math import sin, cos

#  scaling in x direction where m is the scaling factor
mx,my,mz=5,0,0
A=[[mx,0,0,0],[0,my,0,0],[0,0,mz,0],[0,0,0,1]]
A=np.matrix(A)

#  rotation along Z direction is given by
theta = np.deg2rad(30)
B = ([[cos(theta), -sin(theta),0,0],[sin(theta), cos(theta),0,0],[0,0,1,0],[0,0,0,1]])
B=np.matrix(B)


# shear along the Z axis 
sx,sy=2,3
C=[[1,0,sx,0],[0,1,sy,0],[0,0,1,0],[0,0,0,1]]
C=np.matrix(C)

#  transformation matrix

tx,ty,tz=2,1,2
D=[[1,0,0,tx],[0,1,0,ty],[0,0,0,tz],[0,0,0,1]]
D=np.matrix(D)

H=A*B*C*D
print(H)






[[ 4.33012702 -2.5         0.          8.48076211]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          1.        ]]


#  translation matrix

In [52]:


#  translation matrix
tx,ty,tz=8,0,5
D=[[1,0,0,tx],[0,1,0,ty],[0,0,0,tz],[0,0,0,1]]
D=np.matrix(D)

#  scaling in  direction where m is the scaling factor
mx,my,mz=2,2,2
S=[[mx,0,0,0],[0,my,0,0],[0,0,mz,0],[0,0,0,1]]
S=np.matrix(S)
# complete transformation
H=D*S
print("H: ")
print(H)
#  homogenous co-ordinates of A
A=[2,3,9,1]
A=np.matrix(A)
At=np.transpose(A)

print(H*At)







H: 
[[2 0 0 8]
 [0 2 0 0]
 [0 0 0 5]
 [0 0 0 1]]
[[12]
 [ 6]
 [ 5]
 [ 1]]


#  translation matrix

In [6]:
#  rotation along Z direction is given by
theta = np.deg2rad(30)
Z = ([[cos(theta), -sin(theta),0,0],[sin(theta), cos(theta),0,0],[0,0,1,0],[0,0,0,1]])
Z=np.matrix(Z)

#  rotation along X direction is given by
theta = np.deg2rad(180)
X = ([[1,0,0,0],[0,cos(theta), -sin(theta),0],[0,sin(theta), cos(theta),0],[0,0,0,1]])
X=np.matrix(X)

#  rotation along X direction is given by
theta = np.deg2rad(90)
Y = ([[cos(theta),0, sin(theta),0],[0,1,0,0],[-sin(theta),0, cos(theta),0],[0,0,0,1]])
Y=np.matrix(Y)

#  translation matrix
tx,ty,tz=4,-3,7
D=[[1,0,0,tx],[0,1,0,ty],[0,0,0,tz],[0,0,0,1]]
D=np.matrix(D)

#  homogenous co-ordinates of A
A=[5,9,4,1]
A=np.matrix(A)
At=np.transpose(A)

H=Z*Y*X*D
print(H*At)



[[-3.06217783]
 [-8.69615242]
 [-9.        ]
 [ 1.        ]]


decomposition of the projection matrix P(Not compelte)

In [126]:
def matrix_gen(uv, p):
        u=uv[0]   ## creating u row
        b.append(u)
        row_u=p
        row_u= row_u+[0,0,0,0]
        row_u= row_u+[u*p[0],u*p[1],u*p[2],1]
   
        v=uv[1] ## creating v row
        b.append(v)
        row_v=[0,0,0,0]
        row_v=row_v+p
        row_v= row_v+[v*p[0],v*p[1],v*p[2],1]
    
        row_uv=row_u+row_v
    
        return row_uv
    
def b_mat(uv):
        u=uv[0]   ## creating u 
        b.append(u)
        v=uv[1] ## creating v 
        b.append(v)
        return b
    
    

    
    
v_u_list=[[880 ,214],[43, 203],
[270, 197],

[886 ,347],

[745 ,302],

[943 ,128],

[476 ,590],

[419 ,214],

[317 ,335],
[783 ,521],

[235, 427],

[665, 429],

[655 ,362],

[427 ,333],
[412 ,415],
[746,351],

[434,415],

[525 ,234],
[716, 308],
[602, 187]]
points=[[312.747, 309.140, 30.086],

[305.796, 311.649 ,30.356],

[307.694 ,312.358 ,30.418],

[310.149, 307.186 ,29.298],

[311.937, 310.105 ,29.216],

[311.202, 307.572 ,30.682],

[307.106, 306.876 ,28.660],

[309.317, 312.490 ,30.230],

[307.435, 310.151 ,29.318],

[308.253, 306.300 ,28.881],

[306.650, 309.301 ,28.905],

[308.069 ,306.831 ,29.189],

[309.671, 308.834 ,29.029],

[308.255, 309.955 ,29.267],

[307.546, 308.613 ,28.963],

[311.036, 309.206 ,28.913],

[307.518, 308.175 ,29.069],

[309.950, 311.262 ,29.990],

[312.160, 310.772 ,29.080],

[311.988, 312.709 ,30.514]]

matrix=[]
b=[]
for i in v_u_list:
        j=0
        matrix=matrix+matrix_gen(i, points[j])
        b=b+b_mat(i)
        j=j+1

        
# reshaping the matrix to 11xlen points
matrix=np.reshape(matrix,(2*len(v_u_list),11))
matrix=np.matrix(matrix)
# print(matrix)

b=np.matrix(b)
b=np.transpose
# M =np.linalg.lstsq(matrix,b)

# M = np.append(M,1)
# M = np.reshape(M, (3,4))

U, S, Vh = np.linalg.svd(matrix)

#  V = Vh.T
# print(Vh)
M = Vh[-1]
M=np.ravel(M)
# print(M)
M=np.append(M,[1], axis=None)
M = np.reshape(M, (3,4))
M

array([[-4.87799133e-14,  1.05452922e-16,  6.29981523e-14,
         1.00000000e+00],
       [-1.08547005e-13,  9.31514828e-14, -2.71845779e-13,
        -3.00626418e-17],
       [ 2.90354088e-17,  1.10474886e-17,  1.33801383e-11,
         1.00000000e+00]])

In [115]:
# 

H,h=np.hsplit(M, np.array([3, 6]))[0],np.hsplit(M, np.array([3, 6]))[1]
# H_inv= Rt* Kinv
H_inv=np.linalg.inv(H)
# Qr decomposition of H
Rt_Kinv=np.linalg.qr(H)
Rt_Kinv

(array([[-4.09901733e-01,  9.12129282e-01,  8.61309109e-04],
        [-9.12129656e-01, -4.09901789e-01, -1.19572031e-04],
        [ 2.43986993e-04, -8.34638364e-04,  9.99999622e-01]]),
 array([[ 1.19003921e-13, -8.50094526e-14,  2.25400124e-13],
        [ 0.00000000e+00, -3.80867819e-14,  1.57724953e-13],
        [ 0.00000000e+00,  0.00000000e+00,  1.33802200e-11]]))

Question 10

In [125]:
# x=MX

M=[512, -800, 0, 800,
512, 0, -800, 1600,
1 ,0 ,0 ,0]
M=np.reshape(M,(3,4))
M=np.matrix(M)
Xt=[4,0,0,1]
Xt=np.matrix(Xt)
X=np.transpose(Xt)
x=M*X
x/4


matrix([[712.],
        [912.],
        [  1.]])